### ISSUE TITLE
Inference wrong!!

### ISSUE THREAD

**Issue by zhanghanbin3159** [liangdashuang/mobilenetv2_SSD#2]
when I use your pretrained caffemode and the deploy.prototxt, can not detect any object.
the results of class 、confidence 、 bbox are all -1。
can you provide your infer codes？
@liangdashuang

**Comment by liangdashuang** [comment]
@zhanghanbin3159   I  have upload inference file, you can reference to it.

**Comment by zhanghanbin3159** [comment]
thank your reply!
I modify the classes,just have two lable(bg and person).you have 3 categroy.
then I train the model without pretrain model.
the reslut is so bad. **the detection_out has a lot of bbox.**
How did you train your model?

**Comment by zhanghanbin3159** [comment]
its OK

**Comment by gongdalinux** [comment]
@zhanghanbin3159 
> thank your reply!
> I modify the classes,just have two lable(bg and person).you have 3 categroy.
> then I train the model without pretrain model.
> the reslut is so bad. **the detection_out has a lot of bbox.**
> How did you train your model?

I use a pretrain model to train, and the detection_out has a lot of bbox.  How to fix?

**Comment by zhanghanbin3159** [comment]
@gongdalinux add NMS
